// apps/react-vs-angular--react/src/app/app.tsx
import { ESTADOS_ENDPOINT, UnidadeFederativa } from "@hypeit-brasil/ibge-api";
import axios from 'axios';
import { useEffect, useState } from "react";

export interface Todo {
  id: number;
  title: string;
  done: boolean
}


export function App() {

  const [estados, setEstados] = useState([] as UnidadeFederativa[]);
  const [pesquisa, setPesquisa] = useState('');


  useEffect(() => {
    axios.get<UnidadeFederativa[]>(ESTADOS_ENDPOINT).then(
      estados => setEstados(estados.data)
    )
  }, [])



  return (
    <div>
      <h1>Estados brasileiros</h1>
      <input
        value={pesquisa}
        onChange={event => setPesquisa(event.target.value)}
      />
      <ul>
        {
          estados
            .filter(estado => estado.nome.includes(pesquisa))
            .map(estado =>
            <li key={estado.id}>
              { estado.nome }
            </li>
          )
        }
      </ul>
    </div>
  );
}

export default App;

// apps/react-vs-angular-angular/src/app/app.component.ts
import { HttpClient } from "@angular/common/http";
import { Component, OnInit } from '@angular/core';
import { ESTADOS_ENDPOINT, UnidadeFederativa } from '@hypeit-brasil/ibge-api';


@Component({
  selector: 'hypeit-brasil-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {

  estados: UnidadeFederativa[] = [];

  pesquisa = '';

  get estadosFiltrados() {
    return this.estados.filter(estado => estado.nome.includes(this.pesquisa))
  }

  constructor(private http: HttpClient) { }

  ngOnInit(): void {

    this.http.get<UnidadeFederativa[]>(ESTADOS_ENDPOINT).subscribe({
      next: estados => {
        this.estados = estados
      }
    })

  }


}



<h1>Estados brasileiros</h1>
<input [(ngModel)]="pesquisa" type="text" name="" id="">

<ul>
  <li *ngFor="let estado of estadosFiltrados">
    {{ estado.nome }}
  </li>
</ul>
